# Generated by Django 5.1.3 on 2025-04-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="benefits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benefits", models.CharField(max_length=120, verbose_name="Benefits")),
            ],
        ),
    ]
