# Generated by Django 5.1.6 on 2025-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0004_myclubuser_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="myclubuser",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
