# Generated by Django 5.1.6 on 2025-04-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApprovedUser",
        ),
    ]
