# Generated by Django 5.1.6 on 2025-04-04 18:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_delete_approveduser"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedUser",
            fields=[],
            options={
                "verbose_name": "Approved Member",
                "verbose_name_plural": "Approved Members",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
