# Generated by Django 5.1.6 on 2025-04-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_date_of_birth_profile_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
